# ==============================================================================
#                Kernel CONFIG_FOO options Configuration File
# ==============================================================================
# Notes on syntax and guidelines:
#   - Lines starting with '##' are structural header comments (DO NOT UNCOMMENT).
#   - Lines starting with '#' are configurable settings disabled by default.
#   - Uncomment and adjust settings carefully. Ensure you understand the security
#     implications before modifying values.
# ==============================================================================

[config.drivers]

[config.misc]

# Required kernel config options for kgdb
[config.debug]
CONFIG_KGDB=y
CONFIG_KGDB_SERIAL_CONSOLE=y # kgdboc: KGDB over console
CONFIG_KGDB_KDB=y            # optional: built-in KDB shell
CONFIG_FRAME_POINTER=y       # reliable stack traces
CONFIG_DEBUG_INFO=y          # symbol information in vmlinux
CONFIG_GDB_SCRIPTS=y         # GDB python scripts for kernel types
CONFIG_RANDOMIZE_BASE=n      # deactivate KASLR
CONFIG_DEBUG_INFO_DWARF4=y   # DWARF4 format