# SPDX-License-Identifier: GPL-2.0
#
# vim: set ts=8 sw=8 noet tw=80 cc=80 fo+=t :

# building a debug kernel

DEBUG_PACKAGES=(
    linux-headers-amd64
    linux-headers-generic
    linux-headers-$(uname -r)
    dkms

#--- tracing
    #Lttng tracers
    lttng-tools
    lttng-modules-dkms
    python3-lttng

    #trace
    trace-cmd
    strace
    ltrace

#--- analyzis
    linux-perf
    gdb
    gdb-multiarch
    crash
    kexec-tools
    valgrind

    #binary analyzis
    binutils
)

DEBUG_ALIASES=(
    ["decode-strace"]="$SCRIPTS_DIR/decode_stacktrace.sh"
    ["checkpatch"]="$SCRIPTS_DIR/checkpatch.pl"
)